/* generated by tools/build_elf_page.py - do not edit */
window.PAYLOAD_TILES = [
    { title: "pldmgr", description: "Payload Manager. Runs on port 8084.", name: "pldmgr_v0.5.2.elf", key: "pldmgr" }
];
window.PAYLOAD_ART = { dir: "ui/", pfx: "btn-", on: true };
